//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShireDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltest
    {
        public int ID { get; set; }
        public string Company { get; set; }
        public Nullable<int> unitNo { get; set; }
        public string Fluidlevels { get; set; }
        public string Dates { get; set; }
    }
}
